# -*- coding: utf-8 -*-
"""HotelsBooking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mpecY5QTXTUzP94ruO-poZ9ckhkhmc6a
"""

import pandas as pd

file_path = '/content/hotel_booking.csv'

hotel_data = pd.read_csv(file_path)

hotel_data.head(), hotel_data.info()

import matplotlib.pyplot as plt

import seaborn as sns

sns.set(style="whitegrid")

cancellation_rate = hotel_data['is_canceled'].value_counts(normalize=True) * 100

plt.figure(figsize=(8, 6))

sns.barplot(x=cancellation_rate.index, y=cancellation_rate.values, palette="viridis")

plt.title('Booking Cancellation Rate')

plt.xlabel('Is Canceled')

plt.ylabel('Percentage')

plt.xticks([0, 1], ['Not Canceled', 'Canceled'])

plt.show()

plt.figure(figsize=(10, 6))

sns.histplot(hotel_data['lead_time'], bins=50, kde=True, color='blue')

plt.title('Distribution of Lead Time')

plt.xlabel('Lead Time (days)')

plt.ylabel('Frequency')

plt.show()

bookings_by_month = hotel_data['arrival_date_month'].value_counts()

plt.figure(figsize=(12, 6))

sns.barplot(x=bookings_by_month.index, y=bookings_by_month.values, palette="coolwarm")

plt.title('Number of Bookings by Month')

plt.xlabel('Month')

plt.ylabel('Number of Bookings')

plt.xticks(rotation=45)

plt.show()

from google.colab import drive
drive.mount('/content/drive')